### ISSUE TITLE
Primary key support

### ISSUE THREAD

**Issue by kacurez** [keboola/ex-email-attachments#12]
podporuje pigeon primary key?
podla zbezneho nahladu do kodu sa zda ze nie:
https://github.com/keboola/pigeon/blob/master/src/Keboola/Pigeon/RunCommand.php#L113

**Comment by JakubMatejka** [comment]
Přidal jsem parametr `primaryKey` jako pole, ok?

(Fixed by https://github.com/keboola/pigeon/releases/tag/1.5.1)
