### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by padak** [keboola/ex-email-attachments#17]
Ahoj,
mám internal error v klientském projektu. Error je tady https://connection.keboola.com/admin/projects/477/jobs/380525185, Zendesk ticket tady https://keboola.zendesk.com/agent/tickets/8273 a PT log tady https://papertrailapp.com/groups/23635/events?q=docker-0feacf6563f8e53d9f9bd043f5e0363b&focus=922468222744277062

podle KBC to před víkendem jelo, pak se něco změnilo a teď to nejede. Měnili delimitery, primární klíče, apod. Nic co by mělo sypat Internal error. Můžeš se na to, prosím, podívat, @JakubMatejka ?

Díky,
Padák

**Comment by JakubMatejka** [comment]
Může za to zřejmě čárka ve jméně recipienta, namísto ručního parsování jsem objevil http://php.net/manual/en/function.mailparse-rfc822-parse-addresses.php tak už by to mělo být bez problémů
