### ISSUE TITLE
Multiple attachments - only one is processed

### ISSUE THREAD

**Issue by ujovlado** [keboola/ex-email-attachments#18]
3 CSV files:

```
$cat 1.csv 2.csv 3.csv 

key,val
1,val1
2,val2
key,val
3,val3
4,val4
key,val
5,val5
6,val6
```

![screenshot_2018-06-27_17-30-17](https://user-images.githubusercontent.com/419849/41983994-cdc1f334-7a2f-11e8-94df-03872ced69b8.png)

Event `{"processedAttachments":3}`, but only one (in this case last) was uploaded.

Looks like all tables are exported with same name (`data`).

**Comment by ujovlado** [comment]
![screenshot_2018-06-27_17-32-36](https://user-images.githubusercontent.com/419849/41984101-19b6c774-7a30-11e8-8697-9742795898da.png)

**Comment by ujovlado** [comment]
https://github.com/keboola/ex-email-attachments/blob/afb79e7e2816a9554deeb51b9b8462f1581fae2a/src/Keboola/ExEmailAttachments/Action/RunAction.php#L135

**Comment by ujovlado** [comment]
@JakubMatejka napada ti ako to fixnut?

Chvilu som sa v tom vrtal a napadli mi 2 alternativy:

- exportovat to ako sliced file
- exportnut prvy file ako data.csv a ak su tam dalsie odstranit z nich hlavicky a appendnut ich na jeho koniec

**Comment by JakubMatejka** [comment]
@ujovlado A nemělo by se to spíš naimportovat jako tři samostatný soubory? I když, hm, ale spojovat je do jednoho se mi taky moc nezdá, kód se bude zbytečně komplikovat a i na straně klienta je transparentnější když pošle tři samostatný emaily. A nebo je ještě možnost napsat do dokumentace, že se zpracovává jen jeden soubor.

**Comment by ujovlado** [comment]
Ja prave neviem, on v tom tickete tvrdi, ze nejaky "stary email ex" to robil tak, ze ich daval do jednej:
https://keboola.zendesk.com/agent/tickets/8692

Ale asi ak si povieme, ze novy to tak nerobi, tak to tak bude, no .... Neviem si ale uplne predstavit ako sa nad tym postavi nejaka automatizacia, ak to moze (teoreticky) pri kazdom jobe vyexportovat rozny pocet tabuliek.

**Comment by ujovlado** [comment]
Este to teda dovysvetlil v tickete.

Uplne rovnako sa to sprava ked to spracovava 3 emaily naraz. Nasimulovat to ide tak ako pisem hore akurat sa tie 3 prilohy poslu ako 3 samostatne emaily.

T.j. totozny log a importnuty len posledny subor.

To ma mrzi, no z toho logu mi vobec nedoplo, ze ide o spracovanie 3 emailov.

![screenshot_2018-07-04_14-16-06](https://user-images.githubusercontent.com/419849/42276640-d05c714a-7f94-11e8-8659-093c128cd7fc.png)

Takze toto  budu asi 2 samostatne bugy.
