### ISSUE TITLE
Allow forcing timestamp of last processed email

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/ex-email-attachments#21]
Currently if extractor fails there is no way to make it start over as seen bellow:

* orchestration failed due to an error: https://connection.eu-central-1.keboola.com/admin/projects/79/jobs/4327848
* next run starts from after the last: https://connection.eu-central-1.keboola.com/admin/projects/79/jobs/4346698
* so all the emails imported in job 4327848 are lost forever (maybe unless you create new configuration and start over completely).

**Comment by odinuv** [comment]
to neni ve state?

**Comment by tomasfejfar** [comment]
No právě, že je. Tam už je ten nový (který nakonec failnul při nahrávání). Takže ono to už navždycky bude přeskakovat.

**Comment by tomasfejfar** [comment]
Napadlo mě to vyřešit tak, že bych přes API nahrál konfiguraci se změněným statem, který by měl v timestampu datum posledního úspěšného jobu. Ale trochu se bojím, že je to "with great power comes great responsibility" a já prd vím, co všechno by to mohlo ovlivit.

**Comment by odinuv** [comment]
no tak to je spis vec UI, nekde jsme to tlacitko na reset state meli

**Comment by tomasfejfar** [comment]
Ve výsledku si říkám, jestli je to vůbec legitimní use-case. Jestli fakt nedává smysl ten state restartoval low-level. Ta chyba jde za náma a u běžné chyby někde v datech by to spadlo dřív, než se state nastaví.
