### ISSUE TITLE
Preposilani emailu - verifikace

### ISSUE THREAD

**Issue by ErikZigo** [keboola/ex-email-attachments#25]
Narazil jsem na to na Zendesku v ticketu 8953

Jedna se o Gmail, ale dalsi sluzby to budou mit urcite podobne.

Do moji soukrome schranky mi chodi nejake reporty a chci je dostat do KBC.
Vytvorim si teda novy filtr pro preposilani zprav a zadam adresu, kterou mi vygeneroval extractor.

Problem je v tom ze Google vyzaduje overeni teto schranky, takze na ni posle verifikacni kod.
Jediny jak se ho muzu dozvedet, ze napisu k nam na Support.

**Comment by padak** [comment]
Máme Gmail extraktor. Tohle bych vůbec nepodporoval.

**Comment by ErikZigo** [comment]
Ja mam dojem ze si nechavaj posilat nejaky reporty z gooddaty.

U Gmailu potrebujes todle overeni i kdyz si chces vytvorit filtr ze zprav a ten nekam preposilat.

**Comment by padak** [comment]
Jj, ale na GoodData máme extraktor a na Gmail taky - není nutný nic fwdovat

**Comment by tomasfejfar** [comment]
To mi přijde jako dostatečné řešení. Každá služba může mít jiný formát toho potvrzení, ne? 

Jinak jediný způsob jak to udělat mě napadá přepínatelný mail forwarding (z té vygenerované schránky někam).

**Comment by ErikZigo** [comment]
Jezismarja tak jasne ze sluzeb je milion. Davalo by mi smysl podprovat Microsoft/Google, coz stejne jsou asi nejcastejsi pripady.

Ano na GD mame ex, na Gmail taky. Ale myslim ze proste muze existovat situace kdy sluzba umi preposilat reporty jen na jednu adresu. A ty to chce s do KBC a zaroven pro kontrolu sobe. V ty situaci ale nechces, aby KBC bylo autorizovany k cely tvoji schrance.

To byla jen myslenka, takze to tady zaviram.
