### ISSUE TITLE
mysterious data1 table

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/ex-email-attachments#26]
vypadá to, že pokud je v inboxu víc zpráv, generuje to na výstupu víc souborů - a pak to chce importovat jako víc tabulek. v dokumentaci jsem nic nenašel, ve zdrojáku toto

https://github.com/keboola/ex-email-attachments/blob/dbf9188de202f002eae7f8a02cfbb32f55ae4195/src/Keboola/ExEmailAttachments/Action/RunAction.php#L182

je to feature nebo bug? například vypadl jeden pravidelnej job, v inboxu jsou dva maily a už to nemůžu nijak rozběhnout. 

https://connection.keboola.com/admin/projects/232/jobs/477809311

ideální by bylo, kdyby to všechny soubory cpalo do folderu a vyrobilo to k nim manifest, tj. dokázalo by to stáhnout libovolnej počet souborů a ty pak hromadně naimportovat? divím se, že to ještě nikoho nepotkalo.

![image](https://user-images.githubusercontent.com/497675/51235809-b9751380-1970-11e9-8d6c-fc752f40b5b1.png)

```
{
        "parameters": {
            "email": "***@import.keboola.com",
            "delimiter": ";",
            "enclosure": "\"",
            "primaryKey": [],
            "incremental": true
        }
    }
```

**Comment by ondrejhlavacek** [comment]
několik jobů během poslední noci vyfailovalo kvůli docker runneru, těm se neuložil state a zítra budou importovat víc souborů - všem teda vznikne nějaká `data1` tabulka a v `data` budou nekompletní importy (bude chybět to, co je v `data1`).

**Comment by JakubMatejka** [comment]
Myslím že to bylo ohledně tohoto issue: https://github.com/keboola/ex-email-attachments/issues/18

**Comment by JakubMatejka** [comment]
https://github.com/keboola/ex-email-attachments/commit/cc1f6de6cb6d6cffaf2a357226456aee27623610

**Comment by JakubMatejka** [comment]
Tak se to řešilo tady: https://keboola.slack.com/archives/C02C3GZUS/p1530600960000204

**Comment by ondrejhlavacek** [comment]
tak to jsme v knedli!
budem muset identifikovat, jaký konfigurace měly problém a ty pustit znovu, než tam přistane novej email.
a jak to vyřešit teď vůbec nevím, ty dva requesty jsou v přímým rozporu. situace, že v jednom emailu je víc tabulek a těch emailů se zpracuje víc (například při výpadku) je docela pekelná.

**Comment by JakubMatejka** [comment]
A tady k tomu byl PR: https://github.com/keboola/ex-email-attachments/pull/23 Já teda mám problém si tu tehdejší situaci vybavit, ale momentálně mi pořád nedochází, proč se soubory ze dvou příchozích emailů zpracují samostatně. Chápal bych to, když by šlo o dvě přílohy jednoho emailu.

Nebo je to takhle proto, že to jinak nešlo technicky udělat? Už možná vím, vybavuju si, že jsem v úplně původním řešení ty csvčka spojil v extraktoru do jednoho. Jenže pak nefungovaly procesory, když by je bylo třeba před spojením upravit. Varianta tedy byla nechat je zvlášť, aby se pak naimportovaly jako sliced do jedný tabulky, ale to zase nešlo zařídit procesorama?

**Comment by ondrejhlavacek** [comment]
Situace, že v emailu je víc příloh, který přijdou do víc tabulek, není řešitelná bez nějakýho custom řešení. A i to bude totální brainfuck, pokud to budem chtít udělat odolný proti výpadkům. Chtělo by to mrknout, jestli to takhle někdo reálně používá a pokud ne, tak featuru odstranit?

**Comment by ondrejhlavacek** [comment]
ref https://keboola.zendesk.com/agent/tickets/8772
ref https://keboola.zendesk.com/agent/tickets/8692

**Comment by JakubMatejka** [comment]
Doplněno do dokumentace: https://github.com/keboola/ex-email-attachments/pull/27
