### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/ex-email-attachments#7]
Momentálně ui přes json schéma vypadá takto:
![test 2017-12-22 12-32-29](https://user-images.githubusercontent.com/215660/34296739-4753e914-e714-11e7-89c6-4e0b5006c57e.png)
- A nejdřív je přes sync akci `add` třeba vygenerovat email, který se manuálně vepíše do pole `email`. To by se mělo zautomatizovat na straně ui.
- Table Output Mapping je třeba omezit na jednu tabulku
- Extraktor má ještě sync akci `list` na výpis všech emailů pro daný kbc projekt (ale nevím, jestli to bude k něčemu třeba)

**Comment by Halama** [comment]
Teď když na to koukám nebylo by to lepší udělat bez toho konfigurovatelného output mappingu?
Tzn. komponenta by měla default bucket a prostě by to vrátilo jednu tabulku kterou by i pojmenovalo. Stejně jako u nového forecast extractoru https://github.com/keboola/darksky-augmentation#output

**Comment by ondrejhlavacek** [comment]
Jestli tam jsou nějaký sync akce, tak by to asi chtělo vlastní UI, JSON schéma s tím nepočítá a když by se k tomu něco dodělávalo, tak bych to udělal jako custom UI.

**Comment by JakubMatejka** [comment]
@Halama no jo vlastně, udělám

@ondrejhlavacek jasně, proto sháním někoho kdo mi to vyrobí custom ;o)

**Comment by janmichek** [comment]
Muzes mi podrobneji podpsat, jak s tim muzu pomoct?
NEvim presne co znamena 'ui přes json schéma' a 'sync'.
Neda se to pripadne nejak spoji s timto? https://github.com/keboola/indigo-ui/issues/78 Tam jsme taky resili ui/json konfiguraci

**Comment by JakubMatejka** [comment]
@janmichek: Je třeba napsat tý komponentě custom ui (to "univerzální" ui na to nejspíš nebude vhodný). Momentálně je tam vygenerovaný ui přes json schéma (https://developers.keboola.com/extend/registration/configuration-schema/). To má čtyři inputy:
- `email` (required, `string`)
- `incremental` (optional, `boolean`, default: `false`)
- `enclosure` (optional, `char`, default: `"`)
- `delimiter` (optional, `char`, default: `,`)

Problém je v tom, že email je třeba nejdřív vygenerovat synchronní akcí `add` (viz. https://developers.keboola.com/extend/common-interface/actions/) a z jejího outputu vzít vygenerovanou emailovou adresu a ručně ji do toho inputu vložit. A to by právě mělo dělat to ui. Tzn. vytvořím novou konfiguraci a ui asynchronně zavolá tu akci, vezme vygenerovaný email a doplní ho do konfigurace. Volitelný tak budou jen zbývající tři inputy. To je všechno (ten output mapping, co jsem popisoval původně, už není třeba řešit)

**Comment by janmichek** [comment]
>  Je třeba napsat tý komponentě custom ui (to "univerzální" ui na to nejspíš nebude vhodný). Momentálně je tam vygenerovaný ui přes json schéma 

Ja tomu rozumim. Blby je ze nemame zadny podklady pro psani novejch komponent. Jeste jsme se k tomu nedostali. Domnivam se ze by slo pouzit ta sablona z S3, ale je to celkem jedno. Musim ted zacit psat na zeleny louce neco custom, co budeme pozdeji sjednocovat ./ Jde ve finale o 4 inputy, ale koncepcne je to spatne.

> Problém je v tom, že email je třeba nejdřív vygenerovat synchronní akcí add (viz. https://developers.keboola.com/extend/common-interface/actions/) a z jejího outputu vzít vygenerovanou emailovou adresu a ručně ji do toho inputu vložit. A to by právě mělo dělat to ui. Tzn. vytvořím novou konfiguraci a ui asynchronně zavolá tu akci, vezme vygenerovaný email a doplní ho do konfigurace. Volitelný tak budou jen zbývající tři inputy. To je všechno (ten output mapping, co jsem popisoval původně, už není třeba řešit)

Rozumim, uzivateli je jedno odkud se to veme, chce to pohodlne pouzivat.
Mezi radky teda ctu, ze email se zobrazi v disbaled inputu. A chces aby to melo nejakej loader, nez se info dostahne, ok? Predpokladam ze mi pripravis nejakej api call, ja poresim ty uzivatelsky veci

**Comment by JakubMatejka** [comment]
Custom uiček máme plno, tak se dá postupovat podle nich. Pokud tím myslíš, že na to není koncepce, nebo chybí nějaký ui prefabrikáty, tak to teď určitě neřeš, na ně to čekat nemůže. Prostě to jen udělej tak, aby to v budoucnu byl co nejmenší problém upravit. Jj. v zásadě by to mělo doplnit ten email do disablovanýho inputu. Než generování doběhne, tak by tam měl být loader. API call je připravený (to je ta sync akce `add`), v curlu vypadá takto: 

```
curl -X "POST" "https://docker-runner.keboola.com/docker/keboola.ex-pigeon/action/add" \
     -H 'Content-Type: text/plain; charset=utf-8' \
     -H 'x-storageapi-token: TOKEN' \
     -d $'{"configData": {"parameters": {}}}
```
A odpověď vypadá cca takto:

```
{
  "email": "313-5a3cb16b0f0dc@import.keboola.com"
}
```
(http://take.ms/SMHRo)

**Comment by janmichek** [comment]
Dik za pripravu, pokusim se poresit behem dneska

**Comment by ondrejhlavacek** [comment]
Na delimiter máme v UI custom input - https://github.com/keboola/kbc-ui/blob/master/src/scripts/react/common/CsvDelimiterInput.jsx, handluje tak nějak rozumně `\t` delimiter.

**Comment by janmichek** [comment]
Vzhledem k tomu ze jsem zadne ui pro komponentu jeste nepsal, tak se tim musim trochu prokousat. Az budu mit zakladni init a routy pro extraktor, potom to uz bude hracka. Je neco co bych mel vedet pri psani extractoru, mame nejaky guide?
Dosavadni init progres zatim tady, neda se rict ze by to zatim fungovalo xD
https://github.com/keboola/kbc-ui/tree/ui-pigeon

**Comment by ondrejhlavacek** [comment]
Je konfigurace v UI 1:1 ke konfiguraci komponenty?

**Comment by janmichek** [comment]
Nejspis ne -> jeden input chceme aby si dotahnul data API callem. Jinak na  90% to bude stejny

**Comment by janmichek** [comment]
Dosavadni progres. Uz jsem ti povedlo requestnout a osetrit request. Zbyva tomu postavit nejaky frontend .]   
![token error](https://user-images.githubusercontent.com/15363559/34885278-bb8bbe40-f7bf-11e7-8a76-b87e083424c2.gif)

**Comment by janmichek** [comment]
@JakubMatejka porad na tom delam, dneska docela posun .]
Pisu ohledne toho ze jsem si vsimnul typo, muzes to fixnout pls?
Vraci mi to v configDatech key "delimeter", spravne anglicky je to "delimiter"

**Comment by janmichek** [comment]
https://github.com/keboola/pigeon/issues/7

**Comment by janmichek** [comment]
ALternativne nabizim jeste prihozeni ikonky extraktoru

**Comment by janmichek** [comment]
@ondrejhlavacek https://github.com/keboola/pigeon/issues/7#issuecomment-355958432

fajn pouzil jsem tu Delimiter komponentu. Trosku mi tam mrska ze do props se michaji funkcni a stylovy veci. V tomhle pripade si myslim ze to neni nutny, ale dik .]
