### ISSUE TITLE
Support processors

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/ex-email-attachments#9]
- když se oddělí incremental v extrakci a v loadu, dají se dělat zajímavý věci. přesně totéž jsem řešil v S3 extraktoru, kde jsem incremental v extraktoru přejmenoval na `newFilesOnly`, kterej použije state, a je to nezávislý na loadu do Storage
- pokud S3 extraktor stáhne víc souborů, dá je do jednoho adresáře a chová se k tomu jako ke slicovaný tabulce
- ad procesor - https://github.com/keboola/processor-create-manifest, snippet použití je vidět třeba tady - https://github.com/keboola/kbc-ui/blob/03fe7fda3ad8546890d3bdc438a90a57866a8415/src/scripts/modules/ex-aws-s3/adapters/row.spec.def.js#L18

**Comment by pocin** [comment]
Ahoj, fungujou uz processory, pripadne je nejaky casovy odhad kdy by mohly?

**Comment by JakubMatejka** [comment]
Zatím ne, určitě ale až potom co budou mít dořešený ui a oficiálně je vypublikujeme.

**Comment by ondrejhlavacek** [comment]
@pocin ještě to prozkoumám a dám vědět

**Comment by ondrejhlavacek** [comment]
@pocin tak jsem vyzkoušel jednoduchej procesor `skip-lines` a ten zabral. V UI to nemá žádnou oporu (a ani to teď měnit nebudem), ale můžeš si procesory přidat přes API, např.

```
curl -X "PUT" "https://connection.keboola.com/v2/storage/components/keboola.ex-email-attachments/configs/364121243" \
     -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' \
     -H 'X-Storageapi-Token: ***' \
     --data-urlencode "configuration={
    \"parameters\": {
        \"email\": \"***@import.keboola.com\",
        \"delimiter\": \",\",
        \"enclosure\": \"\\\"\",
        \"primaryKey\": [],
        \"incremental\": false
    },
    \"processors\": {
        \"after\": [
            {
                \"definition\": {
                    \"component\": \"keboola.processor-skip-lines\"
                },
                \"parameters\": {
                    \"lines\": 1
                }
            }
        ]
    }
}" \
     --data-urlencode "changeDescription=Add processors"
```

Po tomhle requestu se udělá nová verze konfigurace, ale v UI nebude vidět žádná změna. Doporučil bych do description uvést, že tam je zkonfigurovaný procesor a ať to nikdo dál neupravuje, to by mohlo zabrat. 

Dej vědět, kdybys nad tím nějak tápal a jestli ti to takhle stačí.
